apiVersion: v1
kind: Secret
metadata:
  name: uptime-kuma-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  MYSQL_DATABASE: {{ .Values.database.name | quote }}
  MYSQL_USER: {{ .Values.database.user | quote }}
  MYSQL_PASSWORD: {{ .Values.database.password | quote }}
