name: epub-web

services:
  epub-web:
    container_name: epub-web
    platform: linux/amd64
    environment:
      EPUB_WEB_MAX_UPLOAD_SIZE: 256
      EPUB_WEB_MAX_PAGES: 500
      EPUB_WEB_WORKERS: 8
      EPUB_WEB_REQUEST_TIMEOUT: 90s
      EPUB_WEB_SHUTDOWN_TIMEOUT: 15s
    image: ghcr.io/publira/epub-web:1.1.3@sha256:d07b28d94863d1782a9638d33b8d1f97cc29ea989a779333aaa3aa45f060f001
    ports:
      - 127.0.0.1:8085:8080
    restart: always
