global:
  scrape_interval: 15s

scrape_configs:
  - static_configs:
      - targets: ['localhost:9090']
    job_name: prometheus

  - static_configs:
      - targets: ['node-exporter:9100']
    job_name: node

  - metrics_path: /snmp
    params:
      auth: [public_v2]
      module: [yamaha_rt]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
    static_configs:
      - targets: [192.168.100.1]
    job_name: snmp

  - static_configs:
      - targets: ['snmp-exporter:9116']
    job_name: snmp_exporter

  - static_configs:
      - targets: ['grafana:3000']
    job_name: grafana
