services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      KUBECONFIG: /k8s/kubeconfig.yaml
    network_mode: service:k3s
    volumes:
      - ../..:/workspaces:cached
      - k3s-kubeconfig:/k8s:ro

  k3s:
    command: server --disable=traefik --disable-kube-proxy --flannel-backend=none --disable-network-policy --tls-san 127.0.0.1
    environment:
      K3S_KUBECONFIG_OUTPUT: /k8s/kubeconfig.yaml
      K3S_KUBECONFIG_MODE: "666"
    image: rancher/k3s:v1.35.4-k3s1@sha256:475e036b3fd595472c13ec708c148ffd95459d5f9e40e6df76ba4d5b27098570
    privileged: true
    volumes:
      - k3s-kubeconfig:/k8s
      - type: bind
        source: /sys/fs/bpf
        target: /sys/fs/bpf
        bind:
          propagation: shared
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        bind:
          propagation: shared

volumes:
  k3s-kubeconfig:
