apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alloy
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.alloy: |
    prometheus.scrape "alloy" {
      forward_to      = [prometheus.remote_write.default.receiver]
      job_name        = "alloy"
      scrape_interval = "15s"
      targets         = [
        {"__address__" = "localhost:12345", group = "infrastructure", service = "alloy"},
      ]
    }

    prometheus.remote_write "default" {
      endpoint {
        url = "http://prometheus:9090/api/v1/write"

        basic_auth {
          username = sys.env("ALLOY_PROMETHEUS_USERNAME")
          password = sys.env("ALLOY_PROMETHEUS_PASSWORD")
        }
      }
    }
