apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: grafana
        static_configs:
          - targets: ['grafana:80']

      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']

      - job_name: node
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: snmp_exporter
        static_configs:
          - targets: ['snmp-exporter:9116']
      {{- range .Values.prometheus.snmp.targets }}
      - job_name: snmp_{{ .address | replace "." "_" }}
        metrics_path: /snmp
        params:
          auth: [{{ .auth }}]
          module: [{{ .module }}]
        static_configs:
          - targets: [{{ .address | quote }}]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: snmp-exporter:9116
      {{- end }}
