image:
  repository: ghcr.io/publira/epub-web
  tag: "1.1.4@sha256:617baa62bdb9b5d66ea45da2a8ec9ea51f363d464c4692803aa598728a18eaec"

env:
  maxUploadSize: "256"
  maxPages: "500"
  workers: "8"
  requestTimeout: 90s
  shutdownTimeout: 15s

service: {}

ingress:
  enabled: true
  hostname: epub.ykzts.com
  gateway:
    name: gateway
    namespace: grafana
