{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  parentRefs:
    - name: {{ .Values.ingress.gateway.name }}
      namespace: {{ .Values.ingress.gateway.namespace }}
      sectionName: https
  hostnames:
    - {{ .Values.ingress.hostname | quote }}
  rules:
    - filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            set:
              - name: Content-Security-Policy
                value: "base-uri 'self'; connect-src 'self' https://pay.futo.org https://static.immich.cloud https://tiles.immich.cloud; default-src 'none'; font-src 'self'; frame-ancestors 'none'; img-src 'self' data: blob:; manifest-src 'self'; media-src 'self'; sandbox allow-downloads allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://www.gstatic.com; script-src-attr 'none'; style-src 'self' 'unsafe-inline'; worker-src 'self' blob:"
              - name: Cross-Origin-Embedder-Policy
                value: require-cors
              - name: Cross-Origin-Opener-Policy
                value: same-origin
              - name: Cross-Origin-Resource-Policy
                value: same-origin
              - name: Permissions-Policy
                value: "camera=(), display-capture=(), geolocation=(self), microphone=()"
              - name: Referrer-Policy
                value: no-referrer
              - name: Strict-Transport-Security
                value: max-age=31536000
              - name: X-Content-Type-Options
                value: nosniff
              - name: X-Frame-Options
                value: DENY
            remove:
              - Server
              - X-Powered-By
      backendRefs:
        - name: immich-server
          port: 2283
{{- end }}
