apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.libraryStorage | default "100Gi" }}
