name: uptime-kuma

services:
  database:
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_ROOT_HOST: localhost
      MYSQL_USER: ${MYSQL_USER}
    image: mariadb:12.2.2-noble@sha256:e16f61b8f6ed25111adbb1c5c19bbc2904efc8ed14029999af0cbe1c7ae18bf1
    restart: always
    volumes:
      - /opt/uptime-kuma/mariadb:/var/lib/mysql

  uptime-kuma:
    container_name: uptime-kuma
    depends_on:
      database:
        condition: service_started
    environment:
      UPTIME_KUMA_DB_HOSTNAME: database
      UPTIME_KUMA_DB_NAME: ${MYSQL_DATABASE}
      UPTIME_KUMA_DB_PASSWORD: ${MYSQL_PASSWORD}
      UPTIME_KUMA_DB_PORT: 3306
      UPTIME_KUMA_DB_TYPE: mariadb
      UPTIME_KUMA_DB_USERNAME: ${MYSQL_USER}
    image: ghcr.io/louislam/uptime-kuma:2.2.1@sha256:7337368a77873f159435de9ef09567f68c31285ed5f951dec36256c4b267ee44
    ports:
      - 127.0.0.1:3001:3001
    restart: always
