apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epub-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ykzts/stzky-compose.git
    targetRevision: main
    path: k8s/epub-web
  destination:
    server: https://kubernetes.default.svc
    namespace: epub-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
